Remove undefined variable in init.d script

diff --git a/init/gstd.in b/init/gstd.in
--- a/init/gstd.in
+++ b/init/gstd.in
@@ -23,7 +23,7 @@ manage_dir()
     #Set the owner
     chown "$user" "$dir";
     if [ $? -ne 0 ]; then
-        echo "GstD init: Error, cannot change $dir owner to $user:$group" 1>&2;
+        echo "GstD init: Error, cannot change $dir owner to $user" 1>&2;
         exit 1
     fi
 }
